-- Users table seeds here

INSERT INTO menu_items (name, description, image_url, price) VALUES ('Ranch Chicken Burrito', 'Flour tortilla, grilled chicken, rice, lettuce, tomato & ranch sauce.' , 'https://storage.googleapis.com/ueat-assets/fb453227-3581-495c-831c-5c5b4ae072cd.jpg', 689);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Classic Refrito Bean Burrito', 'Flour tortilla, refried beans topped with cheddar cheese, lettuce, tomato & sour cream.' , 'https://storage.googleapis.com/ueat-assets/4daa7c3f-d5e8-4f9f-9c18-43a0b042e613.jpg', 619);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Classic Beef Burrito', 'Seasoned ground beef, cheddar cheese, fresh lettuce and tomatoes topped with sour cream and rolled into a flour tortilla.','https://storage.googleapis.com/ueat-assets/a4185d2b-7bd6-4c70-a58d-825517eebd31.jpg', 689);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Beef Taco', 'Specially seasoned ground beef, cheddar cheese, fresh lettuce and tomato.' , 'https://storage.googleapis.com/ueat-assets/27343754-4334-4ed9-9a12-d540759f35cc.jpg', 344);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Chicken Taco', 'Delicious marinated chicken, cheddar cheese, fresh lettuce and tomato.' , 'http://partaste.com/worldrecipes/wp-content/uploads/sites/2/2015/06/tacos_de_pollo.jpg', 493);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Ground Beef Burrito Bowl', 'Rice, refrito bean, queso, lettuce, onion, salsa fresca, guacamole & sour cream.' , 'https://storage.googleapis.com/ueat-assets/70bcd28c-48e1-49de-a2b6-189d2e11fdb3.jpg', 949);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Black Bean & Taco Salad', 'Crisp tortilla bowl, black beans, corn, cheddar cheese, salsa fresca, corn tortilla chips. Gluten friendly taco salad is made without salad bowl and taco chip toppings.' , 'https://storage.googleapis.com/ueat-assets/979b7f4f-f6f9-44d6-ba7b-136bd1fcff2b.jpg', 1049);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Mexi-Fries® Deluxe', 'Our delicious Mexi-Fries topped with creamy cheese sauce, specially seasoned ground beef topped with sour cream and salsa fresca.','https://tacotimecanada.com/wp-content/uploads/2020/12/TT_MexiFries_Deluxe.jpg', 574);
INSERT INTO menu_items (name, description, image_url, price) VALUES ('Jr. Chicken Burrito Combo', 'Chicken Burrito Combo, Includes regular size original mexi fries® & small fountain pop.' , 'https://storage.googleapis.com/ueat-assets/d501094c-b735-49b5-ae32-ff256aad7a39.jpg',649 );
