-- Users table seeds here

INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (0, 0, ' Ranch Chicken Burrito', 'Flour tortilla, grilled chicken, rice, lettuce, tomato & ranch sauce.' , 'https://storage.googleapis.com/ueat-assets/fb453227-3581-495c-831c-5c5b4ae072cd.jpg', 689);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (1, 0, ' Classic Refrito Bean Burrito', 'Flour tortilla, refried beans topped with cheddar cheese, lettuce, tomato & sour cream.' , 'https://storage.googleapis.com/ueat-assets/4daa7c3f-d5e8-4f9f-9c18-43a0b042e613.jpg', 619);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (2, 0, ' Classic Beef Burrito', 'Seasoned ground beef, cheddar cheese, fresh lettuce and tomatoes topped with sour cream and rolled into a flour tortilla.','https://storage.googleapis.com/ueat-assets/a4185d2b-7bd6-4c70-a58d-825517eebd31.jpg', 689);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (3, 1, ' Beef Taco', 'Specially seasoned ground beef, cheddar cheese, fresh lettuce and tomato.' , 'https://storage.googleapis.com/ueat-assets/27343754-4334-4ed9-9a12-d540759f35cc.jpg', 344);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (4, 1, ' Marinated Chicken Taco', 'Delicious marinated chicken, cheddar cheese, fresh lettuce and tomato.' , 'https://storage.googleapis.com/ueat-assets/b15599ab-b1c5-4d90-aefa-6134ab5e4b20.jpg', 493);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (5, 2, ' Ground Beef Burrito Bowl', 'Rice, refrito bean, queso, lettuce, onion, salsa fresca, guacamole & sour cream.' , 'https://storage.googleapis.com/ueat-assets/70bcd28c-48e1-49de-a2b6-189d2e11fdb3.jpg', 949);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (6, 3, ' Black Bean & Taco Salad', 'Crisp tortilla bowl, black beans, corn, cheddar cheese, salsa fresca, corn tortilla chips. Gluten friendly taco salad is made without salad bowl and taco chip toppings.' , 'https://storage.googleapis.com/ueat-assets/979b7f4f-f6f9-44d6-ba7b-136bd1fcff2b.jpg', 1049);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (7, 4, ' Mexi-Fries® Deluxe', 'Our delicious Mexi-Fries topped with creamy cheese sauce, specially seasoned ground beef topped with sour cream and salsa fresca.','https://tacotimecanada.com/wp-content/uploads/2020/12/TT_MexiFries_Deluxe.jpg', 574);
INSERT INTO menu_items (id, category_id, name, description, image_url, price) VALUES (8, 4, ' Jr. Chicken Burrito Combo', 'Chicken Burrito Combo, Includes regular size original mexi fries® & small fountain pop.' , 'https://storage.googleapis.com/ueat-assets/d501094c-b735-49b5-ae32-ff256aad7a39.jpg',649 );
